/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.politrons.avro.rpc;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface CustomAvroRPC {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"CustomAvroRPC\",\"namespace\":\"com.politrons.avro.rpc\",\"types\":[{\"type\":\"record\",\"name\":\"Message\",\"fields\":[{\"name\":\"to\",\"type\":\"string\"},{\"name\":\"from\",\"type\":\"string\"},{\"name\":\"body\",\"type\":\"string\"}]}],\"messages\":{\"send\":{\"request\":[{\"name\":\"message\",\"type\":\"Message\"}],\"response\":\"string\"}}}");
  /**
   */
  java.lang.CharSequence send(com.politrons.avro.rpc.Message message) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends CustomAvroRPC {
    public static final org.apache.avro.Protocol PROTOCOL = com.politrons.avro.rpc.CustomAvroRPC.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void send(com.politrons.avro.rpc.Message message, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
  }
}